[package]
name = "jurnalo"
version = "0.1.0"
edition = "2021"
default-run = "jurnalo"
readme = "README.md"
repository = "https://github.com/meee-low/jurnalo/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "0.12.4"

[[bin]]
name = "jurnalo"
path = "src/main.rs"
